name: 'Semantic Release'

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    name: 'Semantic Release'
    uses: lsdopen/.github/.github/workflows/terraform-module-semantic-release.yaml@main
